// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1-devel
// 	protoc        v3.21.8
// source: rental/constant.proto

package rental

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RateType int32

const (
	RateType_STALL_RENTAL_RATE   RateType = 0
	RateType_STALL_RIGHTS_RATE   RateType = 1
	RateType_STALL_SECURITY_BOND RateType = 2
	RateType_OTHER_RATES         RateType = 3
)

// Enum value maps for RateType.
var (
	RateType_name = map[int32]string{
		0: "STALL_RENTAL_RATE",
		1: "STALL_RIGHTS_RATE",
		2: "STALL_SECURITY_BOND",
		3: "OTHER_RATES",
	}
	RateType_value = map[string]int32{
		"STALL_RENTAL_RATE":   0,
		"STALL_RIGHTS_RATE":   1,
		"STALL_SECURITY_BOND": 2,
		"OTHER_RATES":         3,
	}
)

func (x RateType) Enum() *RateType {
	p := new(RateType)
	*p = x
	return p
}

func (x RateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RateType) Descriptor() protoreflect.EnumDescriptor {
	return file_rental_constant_proto_enumTypes[0].Descriptor()
}

func (RateType) Type() protoreflect.EnumType {
	return &file_rental_constant_proto_enumTypes[0]
}

func (x RateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RateType.Descriptor instead.
func (RateType) EnumDescriptor() ([]byte, []int) {
	return file_rental_constant_proto_rawDescGZIP(), []int{0}
}

type OtherRateDetail int32

const (
	OtherRateDetail_NEW_STALL_APPLICATION_FEE      OtherRateDetail = 0
	OtherRateDetail_RENEWAL_STALL_APPLICATION_FEE  OtherRateDetail = 1
	OtherRateDetail_TRANSFER_STALL_APPLICATION_FEE OtherRateDetail = 2
	OtherRateDetail_TRANSFER_FEE                   OtherRateDetail = 3
	OtherRateDetail_REPAIR_PERMIT_FEE              OtherRateDetail = 4
)

// Enum value maps for OtherRateDetail.
var (
	OtherRateDetail_name = map[int32]string{
		0: "NEW_STALL_APPLICATION_FEE",
		1: "RENEWAL_STALL_APPLICATION_FEE",
		2: "TRANSFER_STALL_APPLICATION_FEE",
		3: "TRANSFER_FEE",
		4: "REPAIR_PERMIT_FEE",
	}
	OtherRateDetail_value = map[string]int32{
		"NEW_STALL_APPLICATION_FEE":      0,
		"RENEWAL_STALL_APPLICATION_FEE":  1,
		"TRANSFER_STALL_APPLICATION_FEE": 2,
		"TRANSFER_FEE":                   3,
		"REPAIR_PERMIT_FEE":              4,
	}
)

func (x OtherRateDetail) Enum() *OtherRateDetail {
	p := new(OtherRateDetail)
	*p = x
	return p
}

func (x OtherRateDetail) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OtherRateDetail) Descriptor() protoreflect.EnumDescriptor {
	return file_rental_constant_proto_enumTypes[1].Descriptor()
}

func (OtherRateDetail) Type() protoreflect.EnumType {
	return &file_rental_constant_proto_enumTypes[1]
}

func (x OtherRateDetail) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OtherRateDetail.Descriptor instead.
func (OtherRateDetail) EnumDescriptor() ([]byte, []int) {
	return file_rental_constant_proto_rawDescGZIP(), []int{1}
}

var File_rental_constant_proto protoreflect.FileDescriptor

var file_rental_constant_proto_rawDesc = []byte{
	0x0a, 0x15, 0x72, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x72, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x2a,
	0x62, 0x0a, 0x08, 0x52, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x53,
	0x54, 0x41, 0x4c, 0x4c, 0x5f, 0x52, 0x45, 0x4e, 0x54, 0x41, 0x4c, 0x5f, 0x52, 0x41, 0x54, 0x45,
	0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x54, 0x41, 0x4c, 0x4c, 0x5f, 0x52, 0x49, 0x47, 0x48,
	0x54, 0x53, 0x5f, 0x52, 0x41, 0x54, 0x45, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x53, 0x54, 0x41,
	0x4c, 0x4c, 0x5f, 0x53, 0x45, 0x43, 0x55, 0x52, 0x49, 0x54, 0x59, 0x5f, 0x42, 0x4f, 0x4e, 0x44,
	0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x4f, 0x54, 0x48, 0x45, 0x52, 0x5f, 0x52, 0x41, 0x54, 0x45,
	0x53, 0x10, 0x03, 0x2a, 0xa0, 0x01, 0x0a, 0x0f, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x52, 0x61, 0x74,
	0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1d, 0x0a, 0x19, 0x4e, 0x45, 0x57, 0x5f, 0x53,
	0x54, 0x41, 0x4c, 0x4c, 0x5f, 0x41, 0x50, 0x50, 0x4c, 0x49, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e,
	0x5f, 0x46, 0x45, 0x45, 0x10, 0x00, 0x12, 0x21, 0x0a, 0x1d, 0x52, 0x45, 0x4e, 0x45, 0x57, 0x41,
	0x4c, 0x5f, 0x53, 0x54, 0x41, 0x4c, 0x4c, 0x5f, 0x41, 0x50, 0x50, 0x4c, 0x49, 0x43, 0x41, 0x54,
	0x49, 0x4f, 0x4e, 0x5f, 0x46, 0x45, 0x45, 0x10, 0x01, 0x12, 0x22, 0x0a, 0x1e, 0x54, 0x52, 0x41,
	0x4e, 0x53, 0x46, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x4c, 0x4c, 0x5f, 0x41, 0x50, 0x50, 0x4c,
	0x49, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x46, 0x45, 0x45, 0x10, 0x02, 0x12, 0x10, 0x0a,
	0x0c, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x46, 0x45, 0x52, 0x5f, 0x46, 0x45, 0x45, 0x10, 0x03, 0x12,
	0x15, 0x0a, 0x11, 0x52, 0x45, 0x50, 0x41, 0x49, 0x52, 0x5f, 0x50, 0x45, 0x52, 0x4d, 0x49, 0x54,
	0x5f, 0x46, 0x45, 0x45, 0x10, 0x04, 0x42, 0x31, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x72,
	0x73, 0x2e, 0x72, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x50, 0x01, 0x5a, 0x1d, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x2f, 0x72, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_rental_constant_proto_rawDescOnce sync.Once
	file_rental_constant_proto_rawDescData = file_rental_constant_proto_rawDesc
)

func file_rental_constant_proto_rawDescGZIP() []byte {
	file_rental_constant_proto_rawDescOnce.Do(func() {
		file_rental_constant_proto_rawDescData = protoimpl.X.CompressGZIP(file_rental_constant_proto_rawDescData)
	})
	return file_rental_constant_proto_rawDescData
}

var file_rental_constant_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_rental_constant_proto_goTypes = []interface{}{
	(RateType)(0),        // 0: rental.RateType
	(OtherRateDetail)(0), // 1: rental.OtherRateDetail
}
var file_rental_constant_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rental_constant_proto_init() }
func file_rental_constant_proto_init() {
	if File_rental_constant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rental_constant_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rental_constant_proto_goTypes,
		DependencyIndexes: file_rental_constant_proto_depIdxs,
		EnumInfos:         file_rental_constant_proto_enumTypes,
	}.Build()
	File_rental_constant_proto = out.File
	file_rental_constant_proto_rawDesc = nil
	file_rental_constant_proto_goTypes = nil
	file_rental_constant_proto_depIdxs = nil
}
