// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1-devel
// 	protoc        v3.15.8
// source: market/floor.proto

package market

import (
	common "gateway-service/client/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

///////////////////////////////////////////////////////////////////
// Shared payloads
///////////////////////////////////////////////////////////////////
type Floor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FloorplanId     string   `protobuf:"bytes,1,opt,name=floorplan_id,json=floorplanId,proto3" json:"floorplan_id"`
	Name            string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Code            string   `protobuf:"bytes,3,opt,name=code,proto3" json:"code"`
	Image           string   `protobuf:"bytes,4,opt,name=image,proto3" json:"image"`
	PreviousVersion string   `protobuf:"bytes,5,opt,name=previous_version,json=previousVersion,proto3" json:"previous_version"`
	FloorData       string   `protobuf:"bytes,6,opt,name=floor_data,json=floorData,proto3" json:"floor_data"`
	Stalls          []*Stall `protobuf:"bytes,7,rep,name=stalls,proto3" json:"stalls"`
	TotalStalls     int64    `protobuf:"varint,10,opt,name=total_stalls,json=totalStalls,proto3" json:"total_stalls"`
	StallWithDetail int64    `protobuf:"varint,11,opt,name=stall_with_detail,json=stallWithDetail,proto3" json:"stall_with_detail"`
}

func (x *Floor) Reset() {
	*x = Floor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_floor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Floor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Floor) ProtoMessage() {}

func (x *Floor) ProtoReflect() protoreflect.Message {
	mi := &file_market_floor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Floor.ProtoReflect.Descriptor instead.
func (*Floor) Descriptor() ([]byte, []int) {
	return file_market_floor_proto_rawDescGZIP(), []int{0}
}

func (x *Floor) GetFloorplanId() string {
	if x != nil {
		return x.FloorplanId
	}
	return ""
}

func (x *Floor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Floor) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Floor) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Floor) GetPreviousVersion() string {
	if x != nil {
		return x.PreviousVersion
	}
	return ""
}

func (x *Floor) GetFloorData() string {
	if x != nil {
		return x.FloorData
	}
	return ""
}

func (x *Floor) GetStalls() []*Stall {
	if x != nil {
		return x.Stalls
	}
	return nil
}

func (x *Floor) GetTotalStalls() int64 {
	if x != nil {
		return x.TotalStalls
	}
	return 0
}

func (x *Floor) GetStallWithDetail() int64 {
	if x != nil {
		return x.StallWithDetail
	}
	return 0
}

///////////////////////////////////////////////////////////////////
// Create Floor
///////////////////////////////////////////////////////////////////
type CreateFloorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MarketId string `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Image    string `protobuf:"bytes,3,opt,name=image,proto3" json:"image"`
}

func (x *CreateFloorRequest) Reset() {
	*x = CreateFloorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_floor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFloorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFloorRequest) ProtoMessage() {}

func (x *CreateFloorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_floor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFloorRequest.ProtoReflect.Descriptor instead.
func (*CreateFloorRequest) Descriptor() ([]byte, []int) {
	return file_market_floor_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFloorRequest) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *CreateFloorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateFloorRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type CreateFloorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success"`
	// Types that are assignable to Response:
	//	*CreateFloorResponse_Data_
	//	*CreateFloorResponse_Error
	Response isCreateFloorResponse_Response `protobuf_oneof:"response"`
}

func (x *CreateFloorResponse) Reset() {
	*x = CreateFloorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_floor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFloorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFloorResponse) ProtoMessage() {}

func (x *CreateFloorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_floor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFloorResponse.ProtoReflect.Descriptor instead.
func (*CreateFloorResponse) Descriptor() ([]byte, []int) {
	return file_market_floor_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFloorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (m *CreateFloorResponse) GetResponse() isCreateFloorResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *CreateFloorResponse) GetData() *CreateFloorResponse_Data {
	if x, ok := x.GetResponse().(*CreateFloorResponse_Data_); ok {
		return x.Data
	}
	return nil
}

func (x *CreateFloorResponse) GetError() *common.Error {
	if x, ok := x.GetResponse().(*CreateFloorResponse_Error); ok {
		return x.Error
	}
	return nil
}

type isCreateFloorResponse_Response interface {
	isCreateFloorResponse_Response()
}

type CreateFloorResponse_Data_ struct {
	Data *CreateFloorResponse_Data `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type CreateFloorResponse_Error struct {
	Error *common.Error `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*CreateFloorResponse_Data_) isCreateFloorResponse_Response() {}

func (*CreateFloorResponse_Error) isCreateFloorResponse_Response() {}

///////////////////////////////////////////////////////////////////
// Update Floor
///////////////////////////////////////////////////////////////////
type UpdateFloorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FloorplanId string  `protobuf:"bytes,1,opt,name=floorplan_id,json=floorplanId,proto3" json:"floorplan_id"`
	Name        *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name"`
	Image       *string `protobuf:"bytes,3,opt,name=image,proto3,oneof" json:"image"`
	FloorData   *string `protobuf:"bytes,4,opt,name=floor_data,json=floorData,proto3,oneof" json:"floor_data"`
}

func (x *UpdateFloorRequest) Reset() {
	*x = UpdateFloorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_floor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFloorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFloorRequest) ProtoMessage() {}

func (x *UpdateFloorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_floor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFloorRequest.ProtoReflect.Descriptor instead.
func (*UpdateFloorRequest) Descriptor() ([]byte, []int) {
	return file_market_floor_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateFloorRequest) GetFloorplanId() string {
	if x != nil {
		return x.FloorplanId
	}
	return ""
}

func (x *UpdateFloorRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateFloorRequest) GetImage() string {
	if x != nil && x.Image != nil {
		return *x.Image
	}
	return ""
}

func (x *UpdateFloorRequest) GetFloorData() string {
	if x != nil && x.FloorData != nil {
		return *x.FloorData
	}
	return ""
}

type UpdateFloorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success"`
	// Types that are assignable to Response:
	//	*UpdateFloorResponse_Data_
	//	*UpdateFloorResponse_Error
	Response isUpdateFloorResponse_Response `protobuf_oneof:"response"`
}

func (x *UpdateFloorResponse) Reset() {
	*x = UpdateFloorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_floor_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFloorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFloorResponse) ProtoMessage() {}

func (x *UpdateFloorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_floor_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFloorResponse.ProtoReflect.Descriptor instead.
func (*UpdateFloorResponse) Descriptor() ([]byte, []int) {
	return file_market_floor_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateFloorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (m *UpdateFloorResponse) GetResponse() isUpdateFloorResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *UpdateFloorResponse) GetData() *UpdateFloorResponse_Data {
	if x, ok := x.GetResponse().(*UpdateFloorResponse_Data_); ok {
		return x.Data
	}
	return nil
}

func (x *UpdateFloorResponse) GetError() *common.Error {
	if x, ok := x.GetResponse().(*UpdateFloorResponse_Error); ok {
		return x.Error
	}
	return nil
}

type isUpdateFloorResponse_Response interface {
	isUpdateFloorResponse_Response()
}

type UpdateFloorResponse_Data_ struct {
	Data *UpdateFloorResponse_Data `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type UpdateFloorResponse_Error struct {
	Error *common.Error `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*UpdateFloorResponse_Data_) isUpdateFloorResponse_Response() {}

func (*UpdateFloorResponse_Error) isUpdateFloorResponse_Response() {}

///////////////////////////////////////////////////////////////////
// Get Floor
///////////////////////////////////////////////////////////////////
type GetFloorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FloorplanId string `protobuf:"bytes,1,opt,name=floorplan_id,json=floorplanId,proto3" json:"floorplan_id"`
	Draft       *bool  `protobuf:"varint,2,opt,name=draft,proto3,oneof" json:"draft"`
}

func (x *GetFloorRequest) Reset() {
	*x = GetFloorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_floor_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFloorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFloorRequest) ProtoMessage() {}

func (x *GetFloorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_floor_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFloorRequest.ProtoReflect.Descriptor instead.
func (*GetFloorRequest) Descriptor() ([]byte, []int) {
	return file_market_floor_proto_rawDescGZIP(), []int{5}
}

func (x *GetFloorRequest) GetFloorplanId() string {
	if x != nil {
		return x.FloorplanId
	}
	return ""
}

func (x *GetFloorRequest) GetDraft() bool {
	if x != nil && x.Draft != nil {
		return *x.Draft
	}
	return false
}

type GetFloorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success"`
	// Types that are assignable to Response:
	//	*GetFloorResponse_Data_
	//	*GetFloorResponse_Error
	Response isGetFloorResponse_Response `protobuf_oneof:"response"`
}

func (x *GetFloorResponse) Reset() {
	*x = GetFloorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_floor_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFloorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFloorResponse) ProtoMessage() {}

func (x *GetFloorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_floor_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFloorResponse.ProtoReflect.Descriptor instead.
func (*GetFloorResponse) Descriptor() ([]byte, []int) {
	return file_market_floor_proto_rawDescGZIP(), []int{6}
}

func (x *GetFloorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (m *GetFloorResponse) GetResponse() isGetFloorResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *GetFloorResponse) GetData() *GetFloorResponse_Data {
	if x, ok := x.GetResponse().(*GetFloorResponse_Data_); ok {
		return x.Data
	}
	return nil
}

func (x *GetFloorResponse) GetError() *common.Error {
	if x, ok := x.GetResponse().(*GetFloorResponse_Error); ok {
		return x.Error
	}
	return nil
}

type isGetFloorResponse_Response interface {
	isGetFloorResponse_Response()
}

type GetFloorResponse_Data_ struct {
	Data *GetFloorResponse_Data `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type GetFloorResponse_Error struct {
	Error *common.Error `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*GetFloorResponse_Data_) isGetFloorResponse_Response() {}

func (*GetFloorResponse_Error) isGetFloorResponse_Response() {}

///////////////////////////////////////////////////////////////////
// List Floor
///////////////////////////////////////////////////////////////////
type ListFloorsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MarketId string `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id"`
	Draft    *bool  `protobuf:"varint,2,opt,name=draft,proto3,oneof" json:"draft"`
}

func (x *ListFloorsRequest) Reset() {
	*x = ListFloorsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_floor_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFloorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFloorsRequest) ProtoMessage() {}

func (x *ListFloorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_floor_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFloorsRequest.ProtoReflect.Descriptor instead.
func (*ListFloorsRequest) Descriptor() ([]byte, []int) {
	return file_market_floor_proto_rawDescGZIP(), []int{7}
}

func (x *ListFloorsRequest) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *ListFloorsRequest) GetDraft() bool {
	if x != nil && x.Draft != nil {
		return *x.Draft
	}
	return false
}

type ListFloorsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success"`
	// Types that are assignable to Response:
	//	*ListFloorsResponse_Data_
	//	*ListFloorsResponse_Error
	Response isListFloorsResponse_Response `protobuf_oneof:"response"`
}

func (x *ListFloorsResponse) Reset() {
	*x = ListFloorsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_floor_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFloorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFloorsResponse) ProtoMessage() {}

func (x *ListFloorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_floor_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFloorsResponse.ProtoReflect.Descriptor instead.
func (*ListFloorsResponse) Descriptor() ([]byte, []int) {
	return file_market_floor_proto_rawDescGZIP(), []int{8}
}

func (x *ListFloorsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (m *ListFloorsResponse) GetResponse() isListFloorsResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *ListFloorsResponse) GetData() *ListFloorsResponse_Data {
	if x, ok := x.GetResponse().(*ListFloorsResponse_Data_); ok {
		return x.Data
	}
	return nil
}

func (x *ListFloorsResponse) GetError() *common.Error {
	if x, ok := x.GetResponse().(*ListFloorsResponse_Error); ok {
		return x.Error
	}
	return nil
}

type isListFloorsResponse_Response interface {
	isListFloorsResponse_Response()
}

type ListFloorsResponse_Data_ struct {
	Data *ListFloorsResponse_Data `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type ListFloorsResponse_Error struct {
	Error *common.Error `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*ListFloorsResponse_Data_) isListFloorsResponse_Response() {}

func (*ListFloorsResponse_Error) isListFloorsResponse_Response() {}

///////////////////////////////////////////////////////////////////
// Delete stall
///////////////////////////////////////////////////////////////////
type DeleteFloorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FloorplanId string `protobuf:"bytes,1,opt,name=floorplan_id,json=floorplanId,proto3" json:"floorplan_id"`
	DraftOnly   *bool  `protobuf:"varint,2,opt,name=draft_only,json=draftOnly,proto3,oneof" json:"draft_only"`
}

func (x *DeleteFloorRequest) Reset() {
	*x = DeleteFloorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_floor_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFloorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFloorRequest) ProtoMessage() {}

func (x *DeleteFloorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_floor_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFloorRequest.ProtoReflect.Descriptor instead.
func (*DeleteFloorRequest) Descriptor() ([]byte, []int) {
	return file_market_floor_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteFloorRequest) GetFloorplanId() string {
	if x != nil {
		return x.FloorplanId
	}
	return ""
}

func (x *DeleteFloorRequest) GetDraftOnly() bool {
	if x != nil && x.DraftOnly != nil {
		return *x.DraftOnly
	}
	return false
}

type GetFloorCodeAndMarketCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success"`
	// Types that are assignable to Response:
	//	*GetFloorCodeAndMarketCodeResponse_Data_
	//	*GetFloorCodeAndMarketCodeResponse_Error
	Response isGetFloorCodeAndMarketCodeResponse_Response `protobuf_oneof:"response"`
}

func (x *GetFloorCodeAndMarketCodeResponse) Reset() {
	*x = GetFloorCodeAndMarketCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_floor_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFloorCodeAndMarketCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFloorCodeAndMarketCodeResponse) ProtoMessage() {}

func (x *GetFloorCodeAndMarketCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_floor_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFloorCodeAndMarketCodeResponse.ProtoReflect.Descriptor instead.
func (*GetFloorCodeAndMarketCodeResponse) Descriptor() ([]byte, []int) {
	return file_market_floor_proto_rawDescGZIP(), []int{10}
}

func (x *GetFloorCodeAndMarketCodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (m *GetFloorCodeAndMarketCodeResponse) GetResponse() isGetFloorCodeAndMarketCodeResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *GetFloorCodeAndMarketCodeResponse) GetData() *GetFloorCodeAndMarketCodeResponse_Data {
	if x, ok := x.GetResponse().(*GetFloorCodeAndMarketCodeResponse_Data_); ok {
		return x.Data
	}
	return nil
}

func (x *GetFloorCodeAndMarketCodeResponse) GetError() *common.Error {
	if x, ok := x.GetResponse().(*GetFloorCodeAndMarketCodeResponse_Error); ok {
		return x.Error
	}
	return nil
}

type isGetFloorCodeAndMarketCodeResponse_Response interface {
	isGetFloorCodeAndMarketCodeResponse_Response()
}

type GetFloorCodeAndMarketCodeResponse_Data_ struct {
	Data *GetFloorCodeAndMarketCodeResponse_Data `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type GetFloorCodeAndMarketCodeResponse_Error struct {
	Error *common.Error `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*GetFloorCodeAndMarketCodeResponse_Data_) isGetFloorCodeAndMarketCodeResponse_Response() {}

func (*GetFloorCodeAndMarketCodeResponse_Error) isGetFloorCodeAndMarketCodeResponse_Response() {}

type GetPublishedFloorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	ReviewMode bool   `protobuf:"varint,2,opt,name=review_mode,json=reviewMode,proto3" json:"review_mode"`
}

func (x *GetPublishedFloorRequest) Reset() {
	*x = GetPublishedFloorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_floor_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPublishedFloorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublishedFloorRequest) ProtoMessage() {}

func (x *GetPublishedFloorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_floor_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublishedFloorRequest.ProtoReflect.Descriptor instead.
func (*GetPublishedFloorRequest) Descriptor() ([]byte, []int) {
	return file_market_floor_proto_rawDescGZIP(), []int{11}
}

func (x *GetPublishedFloorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetPublishedFloorRequest) GetReviewMode() bool {
	if x != nil {
		return x.ReviewMode
	}
	return false
}

type CreateFloorResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MarketId    string `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id"`
	FloorplanId string `protobuf:"bytes,2,opt,name=floorplan_id,json=floorplanId,proto3" json:"floorplan_id"`
}

func (x *CreateFloorResponse_Data) Reset() {
	*x = CreateFloorResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_floor_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFloorResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFloorResponse_Data) ProtoMessage() {}

func (x *CreateFloorResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_market_floor_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFloorResponse_Data.ProtoReflect.Descriptor instead.
func (*CreateFloorResponse_Data) Descriptor() ([]byte, []int) {
	return file_market_floor_proto_rawDescGZIP(), []int{2, 0}
}

func (x *CreateFloorResponse_Data) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *CreateFloorResponse_Data) GetFloorplanId() string {
	if x != nil {
		return x.FloorplanId
	}
	return ""
}

type UpdateFloorResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FloorplanId string `protobuf:"bytes,1,opt,name=floorplan_id,json=floorplanId,proto3" json:"floorplan_id"`
}

func (x *UpdateFloorResponse_Data) Reset() {
	*x = UpdateFloorResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_floor_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFloorResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFloorResponse_Data) ProtoMessage() {}

func (x *UpdateFloorResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_market_floor_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFloorResponse_Data.ProtoReflect.Descriptor instead.
func (*UpdateFloorResponse_Data) Descriptor() ([]byte, []int) {
	return file_market_floor_proto_rawDescGZIP(), []int{4, 0}
}

func (x *UpdateFloorResponse_Data) GetFloorplanId() string {
	if x != nil {
		return x.FloorplanId
	}
	return ""
}

type GetFloorResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Floor *Floor `protobuf:"bytes,1,opt,name=floor,proto3" json:"floor"`
}

func (x *GetFloorResponse_Data) Reset() {
	*x = GetFloorResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_floor_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFloorResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFloorResponse_Data) ProtoMessage() {}

func (x *GetFloorResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_market_floor_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFloorResponse_Data.ProtoReflect.Descriptor instead.
func (*GetFloorResponse_Data) Descriptor() ([]byte, []int) {
	return file_market_floor_proto_rawDescGZIP(), []int{6, 0}
}

func (x *GetFloorResponse_Data) GetFloor() *Floor {
	if x != nil {
		return x.Floor
	}
	return nil
}

type ListFloorsResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Floors []*Floor `protobuf:"bytes,1,rep,name=floors,proto3" json:"floors"`
}

func (x *ListFloorsResponse_Data) Reset() {
	*x = ListFloorsResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_floor_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFloorsResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFloorsResponse_Data) ProtoMessage() {}

func (x *ListFloorsResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_market_floor_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFloorsResponse_Data.ProtoReflect.Descriptor instead.
func (*ListFloorsResponse_Data) Descriptor() ([]byte, []int) {
	return file_market_floor_proto_rawDescGZIP(), []int{8, 0}
}

func (x *ListFloorsResponse_Data) GetFloors() []*Floor {
	if x != nil {
		return x.Floors
	}
	return nil
}

type GetFloorCodeAndMarketCodeResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FloorCode  string `protobuf:"bytes,1,opt,name=floor_code,json=floorCode,proto3" json:"floor_code"`
	MarketCode string `protobuf:"bytes,2,opt,name=market_code,json=marketCode,proto3" json:"market_code"`
}

func (x *GetFloorCodeAndMarketCodeResponse_Data) Reset() {
	*x = GetFloorCodeAndMarketCodeResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_floor_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFloorCodeAndMarketCodeResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFloorCodeAndMarketCodeResponse_Data) ProtoMessage() {}

func (x *GetFloorCodeAndMarketCodeResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_market_floor_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFloorCodeAndMarketCodeResponse_Data.ProtoReflect.Descriptor instead.
func (*GetFloorCodeAndMarketCodeResponse_Data) Descriptor() ([]byte, []int) {
	return file_market_floor_proto_rawDescGZIP(), []int{10, 0}
}

func (x *GetFloorCodeAndMarketCodeResponse_Data) GetFloorCode() string {
	if x != nil {
		return x.FloorCode
	}
	return ""
}

func (x *GetFloorCodeAndMarketCodeResponse_Data) GetMarketCode() string {
	if x != nil {
		return x.MarketCode
	}
	return ""
}

var File_market_floor_proto protoreflect.FileDescriptor

var file_market_floor_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2f, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x1a, 0x13, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x12, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2f, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa8, 0x02, 0x0a, 0x05, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x12,
	0x21, 0x0a, 0x0c, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x70, 0x6c, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x70, 0x6c, 0x61, 0x6e,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x12, 0x29, 0x0a, 0x10, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x5f, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x72, 0x65, 0x76,
	0x69, 0x6f, 0x75, 0x73, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x66,
	0x6c, 0x6f, 0x6f, 0x72, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x25, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x6c, 0x6c, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x6c, 0x6c, 0x52, 0x06, 0x73, 0x74, 0x61, 0x6c, 0x6c,
	0x73, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x73, 0x74, 0x61, 0x6c, 0x6c,
	0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x74,
	0x61, 0x6c, 0x6c, 0x73, 0x12, 0x2a, 0x0a, 0x11, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x5f, 0x77, 0x69,
	0x74, 0x68, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0f, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x57, 0x69, 0x74, 0x68, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x22, 0x5b, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x61, 0x72, 0x6b, 0x65,
	0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x22, 0xe2, 0x01,
	0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12,
	0x36, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e,
	0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x6f,
	0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x48,
	0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x25, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x1a, 0x46,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x61, 0x72, 0x6b, 0x65,
	0x74, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x70, 0x6c, 0x61, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x6c, 0x6f, 0x6f, 0x72,
	0x70, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0xb1, 0x01, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x6f,
	0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x6c, 0x6f,
	0x6f, 0x72, 0x70, 0x6c, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x70, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01,
	0x12, 0x22, 0x0a, 0x0a, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x09, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x44, 0x61, 0x74,
	0x61, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x08, 0x0a,
	0x06, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x66, 0x6c, 0x6f, 0x6f,
	0x72, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x22, 0xc5, 0x01, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x36, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x25, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x1a, 0x29, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x21, 0x0a, 0x0c, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x70, 0x6c, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x70, 0x6c, 0x61, 0x6e,
	0x49, 0x64, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x59,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x70, 0x6c, 0x61, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x70, 0x6c,
	0x61, 0x6e, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x05, 0x64, 0x72, 0x61, 0x66, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x05, 0x64, 0x72, 0x61, 0x66, 0x74, 0x88, 0x01, 0x01, 0x42,
	0x08, 0x0a, 0x06, 0x5f, 0x64, 0x72, 0x61, 0x66, 0x74, 0x22, 0xc1, 0x01, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x33, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e,
	0x47, 0x65, 0x74, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x25, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x1a, 0x2b, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x23, 0x0a, 0x05,
	0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x61,
	0x72, 0x6b, 0x65, 0x74, 0x2e, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x52, 0x05, 0x66, 0x6c, 0x6f, 0x6f,
	0x72, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x55, 0x0a,
	0x11, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x12,
	0x19, 0x0a, 0x05, 0x64, 0x72, 0x61, 0x66, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00,
	0x52, 0x05, 0x64, 0x72, 0x61, 0x66, 0x74, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x64,
	0x72, 0x61, 0x66, 0x74, 0x22, 0xc7, 0x01, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6c, 0x6f,
	0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x35, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x25, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x1a, 0x2d, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x25, 0x0a, 0x06, 0x66,
	0x6c, 0x6f, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x61,
	0x72, 0x6b, 0x65, 0x74, 0x2e, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x52, 0x06, 0x66, 0x6c, 0x6f, 0x6f,
	0x72, 0x73, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x6a,
	0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x70, 0x6c, 0x61,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x6c, 0x6f, 0x6f,
	0x72, 0x70, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0a, 0x64, 0x72, 0x61, 0x66, 0x74,
	0x5f, 0x6f, 0x6e, 0x6c, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x09, 0x64,
	0x72, 0x61, 0x66, 0x74, 0x4f, 0x6e, 0x6c, 0x79, 0x88, 0x01, 0x01, 0x42, 0x0d, 0x0a, 0x0b, 0x5f,
	0x64, 0x72, 0x61, 0x66, 0x74, 0x5f, 0x6f, 0x6e, 0x6c, 0x79, 0x22, 0xfe, 0x01, 0x0a, 0x21, 0x47,
	0x65, 0x74, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x41, 0x6e, 0x64, 0x4d, 0x61,
	0x72, 0x6b, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x44, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65,
	0x74, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x41, 0x6e,
	0x64, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x25, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x1a, 0x46, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x1d, 0x0a, 0x0a, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x42,
	0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4b, 0x0a, 0x18, 0x47,
	0x65, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x46, 0x6c, 0x6f, 0x6f, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x76, 0x69, 0x65,
	0x77, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x72, 0x65,
	0x76, 0x69, 0x65, 0x77, 0x4d, 0x6f, 0x64, 0x65, 0x32, 0xf6, 0x04, 0x0a, 0x0c, 0x46, 0x6c, 0x6f,
	0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x0b, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x12, 0x1a, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65,
	0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x6f,
	0x6f, 0x72, 0x12, 0x1a, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6c,
	0x6f, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a,
	0x08, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x12, 0x17, 0x2e, 0x6d, 0x61, 0x72, 0x6b,
	0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x46,
	0x6c, 0x6f, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x61,
	0x0a, 0x19, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x41, 0x6e,
	0x64, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x17, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x47, 0x65,
	0x74, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x41, 0x6e, 0x64, 0x4d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x51, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65,
	0x64, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x12, 0x20, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e,
	0x47, 0x65, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x46, 0x6c, 0x6f, 0x6f,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65,
	0x74, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6c, 0x6f, 0x6f,
	0x72, 0x73, 0x12, 0x19, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6c, 0x6f, 0x6f, 0x72,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x13, 0x4c,
	0x69, 0x73, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x46, 0x6c, 0x6f, 0x6f,
	0x72, 0x73, 0x12, 0x17, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x46, 0x69, 0x6e, 0x64,
	0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6d, 0x61,
	0x72, 0x6b, 0x65, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0b, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x12, 0x1a, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65,
	0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4e, 0x6f,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x31, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x72, 0x73, 0x2e, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x50, 0x01, 0x5a, 0x1d, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2d, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x6d, 0x61,
	0x72, 0x6b, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_market_floor_proto_rawDescOnce sync.Once
	file_market_floor_proto_rawDescData = file_market_floor_proto_rawDesc
)

func file_market_floor_proto_rawDescGZIP() []byte {
	file_market_floor_proto_rawDescOnce.Do(func() {
		file_market_floor_proto_rawDescData = protoimpl.X.CompressGZIP(file_market_floor_proto_rawDescData)
	})
	return file_market_floor_proto_rawDescData
}

var file_market_floor_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_market_floor_proto_goTypes = []interface{}{
	(*Floor)(nil),                                  // 0: market.Floor
	(*CreateFloorRequest)(nil),                     // 1: market.CreateFloorRequest
	(*CreateFloorResponse)(nil),                    // 2: market.CreateFloorResponse
	(*UpdateFloorRequest)(nil),                     // 3: market.UpdateFloorRequest
	(*UpdateFloorResponse)(nil),                    // 4: market.UpdateFloorResponse
	(*GetFloorRequest)(nil),                        // 5: market.GetFloorRequest
	(*GetFloorResponse)(nil),                       // 6: market.GetFloorResponse
	(*ListFloorsRequest)(nil),                      // 7: market.ListFloorsRequest
	(*ListFloorsResponse)(nil),                     // 8: market.ListFloorsResponse
	(*DeleteFloorRequest)(nil),                     // 9: market.DeleteFloorRequest
	(*GetFloorCodeAndMarketCodeResponse)(nil),      // 10: market.GetFloorCodeAndMarketCodeResponse
	(*GetPublishedFloorRequest)(nil),               // 11: market.GetPublishedFloorRequest
	(*CreateFloorResponse_Data)(nil),               // 12: market.CreateFloorResponse.Data
	(*UpdateFloorResponse_Data)(nil),               // 13: market.UpdateFloorResponse.Data
	(*GetFloorResponse_Data)(nil),                  // 14: market.GetFloorResponse.Data
	(*ListFloorsResponse_Data)(nil),                // 15: market.ListFloorsResponse.Data
	(*GetFloorCodeAndMarketCodeResponse_Data)(nil), // 16: market.GetFloorCodeAndMarketCodeResponse.Data
	(*Stall)(nil),                                  // 17: market.Stall
	(*common.Error)(nil),                           // 18: common.Error
	(*common.FindByIdRequest)(nil),                 // 19: common.FindByIdRequest
	(*common.NoContentResponse)(nil),               // 20: common.NoContentResponse
}
var file_market_floor_proto_depIdxs = []int32{
	17, // 0: market.Floor.stalls:type_name -> market.Stall
	12, // 1: market.CreateFloorResponse.data:type_name -> market.CreateFloorResponse.Data
	18, // 2: market.CreateFloorResponse.error:type_name -> common.Error
	13, // 3: market.UpdateFloorResponse.data:type_name -> market.UpdateFloorResponse.Data
	18, // 4: market.UpdateFloorResponse.error:type_name -> common.Error
	14, // 5: market.GetFloorResponse.data:type_name -> market.GetFloorResponse.Data
	18, // 6: market.GetFloorResponse.error:type_name -> common.Error
	15, // 7: market.ListFloorsResponse.data:type_name -> market.ListFloorsResponse.Data
	18, // 8: market.ListFloorsResponse.error:type_name -> common.Error
	16, // 9: market.GetFloorCodeAndMarketCodeResponse.data:type_name -> market.GetFloorCodeAndMarketCodeResponse.Data
	18, // 10: market.GetFloorCodeAndMarketCodeResponse.error:type_name -> common.Error
	0,  // 11: market.GetFloorResponse.Data.floor:type_name -> market.Floor
	0,  // 12: market.ListFloorsResponse.Data.floors:type_name -> market.Floor
	1,  // 13: market.FloorService.CreateFloor:input_type -> market.CreateFloorRequest
	3,  // 14: market.FloorService.UpdateFloor:input_type -> market.UpdateFloorRequest
	5,  // 15: market.FloorService.GetFloor:input_type -> market.GetFloorRequest
	19, // 16: market.FloorService.GetFloorCodeAndMarketCode:input_type -> common.FindByIdRequest
	11, // 17: market.FloorService.GetPublishedFloor:input_type -> market.GetPublishedFloorRequest
	7,  // 18: market.FloorService.ListFloors:input_type -> market.ListFloorsRequest
	19, // 19: market.FloorService.ListPublishedFloors:input_type -> common.FindByIdRequest
	9,  // 20: market.FloorService.DeleteFloor:input_type -> market.DeleteFloorRequest
	2,  // 21: market.FloorService.CreateFloor:output_type -> market.CreateFloorResponse
	4,  // 22: market.FloorService.UpdateFloor:output_type -> market.UpdateFloorResponse
	6,  // 23: market.FloorService.GetFloor:output_type -> market.GetFloorResponse
	10, // 24: market.FloorService.GetFloorCodeAndMarketCode:output_type -> market.GetFloorCodeAndMarketCodeResponse
	6,  // 25: market.FloorService.GetPublishedFloor:output_type -> market.GetFloorResponse
	8,  // 26: market.FloorService.ListFloors:output_type -> market.ListFloorsResponse
	8,  // 27: market.FloorService.ListPublishedFloors:output_type -> market.ListFloorsResponse
	20, // 28: market.FloorService.DeleteFloor:output_type -> common.NoContentResponse
	21, // [21:29] is the sub-list for method output_type
	13, // [13:21] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_market_floor_proto_init() }
func file_market_floor_proto_init() {
	if File_market_floor_proto != nil {
		return
	}
	file_market_stall_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_market_floor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Floor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_floor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFloorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_floor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFloorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_floor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFloorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_floor_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFloorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_floor_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFloorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_floor_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFloorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_floor_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFloorsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_floor_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFloorsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_floor_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFloorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_floor_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFloorCodeAndMarketCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_floor_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPublishedFloorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_floor_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFloorResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_floor_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFloorResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_floor_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFloorResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_floor_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFloorsResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_floor_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFloorCodeAndMarketCodeResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_market_floor_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*CreateFloorResponse_Data_)(nil),
		(*CreateFloorResponse_Error)(nil),
	}
	file_market_floor_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_market_floor_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*UpdateFloorResponse_Data_)(nil),
		(*UpdateFloorResponse_Error)(nil),
	}
	file_market_floor_proto_msgTypes[5].OneofWrappers = []interface{}{}
	file_market_floor_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*GetFloorResponse_Data_)(nil),
		(*GetFloorResponse_Error)(nil),
	}
	file_market_floor_proto_msgTypes[7].OneofWrappers = []interface{}{}
	file_market_floor_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*ListFloorsResponse_Data_)(nil),
		(*ListFloorsResponse_Error)(nil),
	}
	file_market_floor_proto_msgTypes[9].OneofWrappers = []interface{}{}
	file_market_floor_proto_msgTypes[10].OneofWrappers = []interface{}{
		(*GetFloorCodeAndMarketCodeResponse_Data_)(nil),
		(*GetFloorCodeAndMarketCodeResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_market_floor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_market_floor_proto_goTypes,
		DependencyIndexes: file_market_floor_proto_depIdxs,
		MessageInfos:      file_market_floor_proto_msgTypes,
	}.Build()
	File_market_floor_proto = out.File
	file_market_floor_proto_rawDesc = nil
	file_market_floor_proto_goTypes = nil
	file_market_floor_proto_depIdxs = nil
}
