// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1-devel
// 	protoc        v3.21.8
// source: market/location.proto

package market

import (
	common "gateway-service/client/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//////////////////////////////////////////////////////////////////
// Request DTO
//////////////////////////////////////////////////////////////////
type ListProvinceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SearchTerm string `protobuf:"bytes,1,opt,name=search_term,json=searchTerm,proto3" json:"search_term"`
}

func (x *ListProvinceRequest) Reset() {
	*x = ListProvinceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_location_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListProvinceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvinceRequest) ProtoMessage() {}

func (x *ListProvinceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_location_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvinceRequest.ProtoReflect.Descriptor instead.
func (*ListProvinceRequest) Descriptor() ([]byte, []int) {
	return file_market_location_proto_rawDescGZIP(), []int{0}
}

func (x *ListProvinceRequest) GetSearchTerm() string {
	if x != nil {
		return x.SearchTerm
	}
	return ""
}

type ListCityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Province   string `protobuf:"bytes,1,opt,name=province,proto3" json:"province"`
	SearchTerm string `protobuf:"bytes,2,opt,name=search_term,json=searchTerm,proto3" json:"search_term"`
}

func (x *ListCityRequest) Reset() {
	*x = ListCityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_location_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCityRequest) ProtoMessage() {}

func (x *ListCityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_location_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCityRequest.ProtoReflect.Descriptor instead.
func (*ListCityRequest) Descriptor() ([]byte, []int) {
	return file_market_location_proto_rawDescGZIP(), []int{1}
}

func (x *ListCityRequest) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *ListCityRequest) GetSearchTerm() string {
	if x != nil {
		return x.SearchTerm
	}
	return ""
}

type ListWardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Province   string `protobuf:"bytes,1,opt,name=province,proto3" json:"province"`
	City       string `protobuf:"bytes,2,opt,name=city,proto3" json:"city"`
	SearchTerm string `protobuf:"bytes,3,opt,name=search_term,json=searchTerm,proto3" json:"search_term"`
}

func (x *ListWardRequest) Reset() {
	*x = ListWardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_location_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWardRequest) ProtoMessage() {}

func (x *ListWardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_location_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWardRequest.ProtoReflect.Descriptor instead.
func (*ListWardRequest) Descriptor() ([]byte, []int) {
	return file_market_location_proto_rawDescGZIP(), []int{2}
}

func (x *ListWardRequest) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *ListWardRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ListWardRequest) GetSearchTerm() string {
	if x != nil {
		return x.SearchTerm
	}
	return ""
}

type GetLocationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Province string `protobuf:"bytes,1,opt,name=province,proto3" json:"province"`
	City     string `protobuf:"bytes,2,opt,name=city,proto3" json:"city"`
	Ward     string `protobuf:"bytes,3,opt,name=ward,proto3" json:"ward"`
}

func (x *GetLocationRequest) Reset() {
	*x = GetLocationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_location_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationRequest) ProtoMessage() {}

func (x *GetLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_location_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationRequest.ProtoReflect.Descriptor instead.
func (*GetLocationRequest) Descriptor() ([]byte, []int) {
	return file_market_location_proto_rawDescGZIP(), []int{3}
}

func (x *GetLocationRequest) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *GetLocationRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *GetLocationRequest) GetWard() string {
	if x != nil {
		return x.Ward
	}
	return ""
}

//////////////////////////////////////////////////////////////////
// Response DTO
//////////////////////////////////////////////////////////////////
type ListProvinceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success"`
	// Types that are assignable to Response:
	//	*ListProvinceResponse_Data_
	//	*ListProvinceResponse_Error
	Response isListProvinceResponse_Response `protobuf_oneof:"response"`
}

func (x *ListProvinceResponse) Reset() {
	*x = ListProvinceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_location_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListProvinceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvinceResponse) ProtoMessage() {}

func (x *ListProvinceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_location_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvinceResponse.ProtoReflect.Descriptor instead.
func (*ListProvinceResponse) Descriptor() ([]byte, []int) {
	return file_market_location_proto_rawDescGZIP(), []int{4}
}

func (x *ListProvinceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (m *ListProvinceResponse) GetResponse() isListProvinceResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *ListProvinceResponse) GetData() *ListProvinceResponse_Data {
	if x, ok := x.GetResponse().(*ListProvinceResponse_Data_); ok {
		return x.Data
	}
	return nil
}

func (x *ListProvinceResponse) GetError() *common.Error {
	if x, ok := x.GetResponse().(*ListProvinceResponse_Error); ok {
		return x.Error
	}
	return nil
}

type isListProvinceResponse_Response interface {
	isListProvinceResponse_Response()
}

type ListProvinceResponse_Data_ struct {
	Data *ListProvinceResponse_Data `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type ListProvinceResponse_Error struct {
	Error *common.Error `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*ListProvinceResponse_Data_) isListProvinceResponse_Response() {}

func (*ListProvinceResponse_Error) isListProvinceResponse_Response() {}

type ListCityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success"`
	// Types that are assignable to Response:
	//	*ListCityResponse_Data_
	//	*ListCityResponse_Error
	Response isListCityResponse_Response `protobuf_oneof:"response"`
}

func (x *ListCityResponse) Reset() {
	*x = ListCityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_location_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCityResponse) ProtoMessage() {}

func (x *ListCityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_location_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCityResponse.ProtoReflect.Descriptor instead.
func (*ListCityResponse) Descriptor() ([]byte, []int) {
	return file_market_location_proto_rawDescGZIP(), []int{5}
}

func (x *ListCityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (m *ListCityResponse) GetResponse() isListCityResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *ListCityResponse) GetData() *ListCityResponse_Data {
	if x, ok := x.GetResponse().(*ListCityResponse_Data_); ok {
		return x.Data
	}
	return nil
}

func (x *ListCityResponse) GetError() *common.Error {
	if x, ok := x.GetResponse().(*ListCityResponse_Error); ok {
		return x.Error
	}
	return nil
}

type isListCityResponse_Response interface {
	isListCityResponse_Response()
}

type ListCityResponse_Data_ struct {
	Data *ListCityResponse_Data `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type ListCityResponse_Error struct {
	Error *common.Error `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*ListCityResponse_Data_) isListCityResponse_Response() {}

func (*ListCityResponse_Error) isListCityResponse_Response() {}

type ListWardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success"`
	// Types that are assignable to Response:
	//	*ListWardResponse_Data_
	//	*ListWardResponse_Error
	Response isListWardResponse_Response `protobuf_oneof:"response"`
}

func (x *ListWardResponse) Reset() {
	*x = ListWardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_location_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWardResponse) ProtoMessage() {}

func (x *ListWardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_location_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWardResponse.ProtoReflect.Descriptor instead.
func (*ListWardResponse) Descriptor() ([]byte, []int) {
	return file_market_location_proto_rawDescGZIP(), []int{6}
}

func (x *ListWardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (m *ListWardResponse) GetResponse() isListWardResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *ListWardResponse) GetData() *ListWardResponse_Data {
	if x, ok := x.GetResponse().(*ListWardResponse_Data_); ok {
		return x.Data
	}
	return nil
}

func (x *ListWardResponse) GetError() *common.Error {
	if x, ok := x.GetResponse().(*ListWardResponse_Error); ok {
		return x.Error
	}
	return nil
}

type isListWardResponse_Response interface {
	isListWardResponse_Response()
}

type ListWardResponse_Data_ struct {
	Data *ListWardResponse_Data `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type ListWardResponse_Error struct {
	Error *common.Error `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*ListWardResponse_Data_) isListWardResponse_Response() {}

func (*ListWardResponse_Error) isListWardResponse_Response() {}

type GetLocationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success"`
	// Types that are assignable to Response:
	//	*GetLocationResponse_Data_
	//	*GetLocationResponse_Error
	Response isGetLocationResponse_Response `protobuf_oneof:"response"`
}

func (x *GetLocationResponse) Reset() {
	*x = GetLocationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_location_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationResponse) ProtoMessage() {}

func (x *GetLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_location_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationResponse.ProtoReflect.Descriptor instead.
func (*GetLocationResponse) Descriptor() ([]byte, []int) {
	return file_market_location_proto_rawDescGZIP(), []int{7}
}

func (x *GetLocationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (m *GetLocationResponse) GetResponse() isGetLocationResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *GetLocationResponse) GetData() *GetLocationResponse_Data {
	if x, ok := x.GetResponse().(*GetLocationResponse_Data_); ok {
		return x.Data
	}
	return nil
}

func (x *GetLocationResponse) GetError() *common.Error {
	if x, ok := x.GetResponse().(*GetLocationResponse_Error); ok {
		return x.Error
	}
	return nil
}

type isGetLocationResponse_Response interface {
	isGetLocationResponse_Response()
}

type GetLocationResponse_Data_ struct {
	Data *GetLocationResponse_Data `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type GetLocationResponse_Error struct {
	Error *common.Error `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*GetLocationResponse_Data_) isGetLocationResponse_Response() {}

func (*GetLocationResponse_Error) isGetLocationResponse_Response() {}

type Location struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocationId string `protobuf:"bytes,1,opt,name=location_id,json=locationId,proto3" json:"location_id"`
	Province   string `protobuf:"bytes,2,opt,name=province,proto3" json:"province"`
	City       string `protobuf:"bytes,3,opt,name=city,proto3" json:"city"`
	District   string `protobuf:"bytes,4,opt,name=district,proto3" json:"district"`
	Zipcode    string `protobuf:"bytes,5,opt,name=zipcode,proto3" json:"zipcode"`
	Ward       string `protobuf:"bytes,6,opt,name=ward,proto3" json:"ward"`
	Address    string `protobuf:"bytes,7,opt,name=address,proto3" json:"address"`
}

func (x *Location) Reset() {
	*x = Location{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_location_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_market_location_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_market_location_proto_rawDescGZIP(), []int{8}
}

func (x *Location) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *Location) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *Location) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Location) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *Location) GetZipcode() string {
	if x != nil {
		return x.Zipcode
	}
	return ""
}

func (x *Location) GetWard() string {
	if x != nil {
		return x.Ward
	}
	return ""
}

func (x *Location) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ListProvinceResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Provinces []string `protobuf:"bytes,1,rep,name=provinces,proto3" json:"provinces"`
}

func (x *ListProvinceResponse_Data) Reset() {
	*x = ListProvinceResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_location_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListProvinceResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvinceResponse_Data) ProtoMessage() {}

func (x *ListProvinceResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_market_location_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvinceResponse_Data.ProtoReflect.Descriptor instead.
func (*ListProvinceResponse_Data) Descriptor() ([]byte, []int) {
	return file_market_location_proto_rawDescGZIP(), []int{4, 0}
}

func (x *ListProvinceResponse_Data) GetProvinces() []string {
	if x != nil {
		return x.Provinces
	}
	return nil
}

type ListCityResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cities []string `protobuf:"bytes,1,rep,name=cities,proto3" json:"cities"`
}

func (x *ListCityResponse_Data) Reset() {
	*x = ListCityResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_location_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCityResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCityResponse_Data) ProtoMessage() {}

func (x *ListCityResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_market_location_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCityResponse_Data.ProtoReflect.Descriptor instead.
func (*ListCityResponse_Data) Descriptor() ([]byte, []int) {
	return file_market_location_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ListCityResponse_Data) GetCities() []string {
	if x != nil {
		return x.Cities
	}
	return nil
}

type ListWardResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Wards []string `protobuf:"bytes,1,rep,name=wards,proto3" json:"wards"`
}

func (x *ListWardResponse_Data) Reset() {
	*x = ListWardResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_location_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWardResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWardResponse_Data) ProtoMessage() {}

func (x *ListWardResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_market_location_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWardResponse_Data.ProtoReflect.Descriptor instead.
func (*ListWardResponse_Data) Descriptor() ([]byte, []int) {
	return file_market_location_proto_rawDescGZIP(), []int{6, 0}
}

func (x *ListWardResponse_Data) GetWards() []string {
	if x != nil {
		return x.Wards
	}
	return nil
}

type GetLocationResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location *Location `protobuf:"bytes,1,opt,name=location,proto3" json:"location"`
}

func (x *GetLocationResponse_Data) Reset() {
	*x = GetLocationResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_location_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLocationResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationResponse_Data) ProtoMessage() {}

func (x *GetLocationResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_market_location_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationResponse_Data.ProtoReflect.Descriptor instead.
func (*GetLocationResponse_Data) Descriptor() ([]byte, []int) {
	return file_market_location_proto_rawDescGZIP(), []int{7, 0}
}

func (x *GetLocationResponse_Data) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

var File_market_location_proto protoreflect.FileDescriptor

var file_market_location_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x1a,
	0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x36, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x65, 0x72, 0x6d, 0x22, 0x4e, 0x0a, 0x0f,
	0x4c, 0x69, 0x73, 0x74, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x65, 0x72, 0x6d, 0x22, 0x62, 0x0a, 0x0f,
	0x4c, 0x69, 0x73, 0x74, 0x57, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12,
	0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x65, 0x72, 0x6d,
	0x22, 0x58, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e,
	0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x61, 0x72, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x77, 0x61, 0x72, 0x64, 0x22, 0xc2, 0x01, 0x0a, 0x14, 0x4c,
	0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x37, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6d, 0x61,
	0x72, 0x6b, 0x65, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x25, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x1a, 0x24, 0x0a,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e,
	0x63, 0x65, 0x73, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0xb4, 0x01, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x33,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d,
	0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x25, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x1a, 0x1e, 0x0a, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x06, 0x63, 0x69, 0x74, 0x69, 0x65, 0x73, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xb2, 0x01, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x57,
	0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x33, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x57, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x25, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x1a, 0x1c, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x61, 0x72,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x77, 0x61, 0x72, 0x64, 0x73, 0x42,
	0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xd0, 0x01, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x36, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6d, 0x61,
	0x72, 0x6b, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x25, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x1a, 0x34, 0x0a, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x2c, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xbf,
	0x01, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08,
	0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x7a, 0x69, 0x70, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x7a, 0x69, 0x70, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x61, 0x72, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x77, 0x61, 0x72, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x32, 0xf1, 0x02, 0x0a, 0x0f, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x4c, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x6e, 0x63, 0x65, 0x73, 0x12, 0x1b, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x41, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x69, 0x74, 0x69, 0x65, 0x73,
	0x12, 0x17, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x69,
	0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6d, 0x61, 0x72, 0x6b,
	0x65, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x61, 0x72,
	0x64, 0x73, 0x12, 0x17, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x57, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6d, 0x61,
	0x72, 0x6b, 0x65, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x4c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x18, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x49, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x2e, 0x6d, 0x61, 0x72, 0x6b,
	0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x47,
	0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x31, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x72, 0x73, 0x2e,
	0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x50, 0x01, 0x5a, 0x1d, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x2f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_market_location_proto_rawDescOnce sync.Once
	file_market_location_proto_rawDescData = file_market_location_proto_rawDesc
)

func file_market_location_proto_rawDescGZIP() []byte {
	file_market_location_proto_rawDescOnce.Do(func() {
		file_market_location_proto_rawDescData = protoimpl.X.CompressGZIP(file_market_location_proto_rawDescData)
	})
	return file_market_location_proto_rawDescData
}

var file_market_location_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_market_location_proto_goTypes = []interface{}{
	(*ListProvinceRequest)(nil),       // 0: market.ListProvinceRequest
	(*ListCityRequest)(nil),           // 1: market.ListCityRequest
	(*ListWardRequest)(nil),           // 2: market.ListWardRequest
	(*GetLocationRequest)(nil),        // 3: market.GetLocationRequest
	(*ListProvinceResponse)(nil),      // 4: market.ListProvinceResponse
	(*ListCityResponse)(nil),          // 5: market.ListCityResponse
	(*ListWardResponse)(nil),          // 6: market.ListWardResponse
	(*GetLocationResponse)(nil),       // 7: market.GetLocationResponse
	(*Location)(nil),                  // 8: market.Location
	(*ListProvinceResponse_Data)(nil), // 9: market.ListProvinceResponse.Data
	(*ListCityResponse_Data)(nil),     // 10: market.ListCityResponse.Data
	(*ListWardResponse_Data)(nil),     // 11: market.ListWardResponse.Data
	(*GetLocationResponse_Data)(nil),  // 12: market.GetLocationResponse.Data
	(*common.Error)(nil),              // 13: common.Error
	(*common.FindByIdsRequest)(nil),   // 14: common.FindByIdsRequest
	(*common.ListResponse)(nil),       // 15: common.ListResponse
}
var file_market_location_proto_depIdxs = []int32{
	9,  // 0: market.ListProvinceResponse.data:type_name -> market.ListProvinceResponse.Data
	13, // 1: market.ListProvinceResponse.error:type_name -> common.Error
	10, // 2: market.ListCityResponse.data:type_name -> market.ListCityResponse.Data
	13, // 3: market.ListCityResponse.error:type_name -> common.Error
	11, // 4: market.ListWardResponse.data:type_name -> market.ListWardResponse.Data
	13, // 5: market.ListWardResponse.error:type_name -> common.Error
	12, // 6: market.GetLocationResponse.data:type_name -> market.GetLocationResponse.Data
	13, // 7: market.GetLocationResponse.error:type_name -> common.Error
	8,  // 8: market.GetLocationResponse.Data.location:type_name -> market.Location
	0,  // 9: market.LocationService.ListProvinces:input_type -> market.ListProvinceRequest
	1,  // 10: market.LocationService.ListCities:input_type -> market.ListCityRequest
	2,  // 11: market.LocationService.ListWards:input_type -> market.ListWardRequest
	14, // 12: market.LocationService.ListLocations:input_type -> common.FindByIdsRequest
	3,  // 13: market.LocationService.GetLocation:input_type -> market.GetLocationRequest
	4,  // 14: market.LocationService.ListProvinces:output_type -> market.ListProvinceResponse
	5,  // 15: market.LocationService.ListCities:output_type -> market.ListCityResponse
	6,  // 16: market.LocationService.ListWards:output_type -> market.ListWardResponse
	15, // 17: market.LocationService.ListLocations:output_type -> common.ListResponse
	7,  // 18: market.LocationService.GetLocation:output_type -> market.GetLocationResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_market_location_proto_init() }
func file_market_location_proto_init() {
	if File_market_location_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_market_location_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListProvinceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_location_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_location_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_location_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLocationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_location_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListProvinceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_location_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_location_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_location_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLocationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_location_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Location); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_location_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListProvinceResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_location_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCityResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_location_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWardResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_location_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLocationResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_market_location_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*ListProvinceResponse_Data_)(nil),
		(*ListProvinceResponse_Error)(nil),
	}
	file_market_location_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*ListCityResponse_Data_)(nil),
		(*ListCityResponse_Error)(nil),
	}
	file_market_location_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*ListWardResponse_Data_)(nil),
		(*ListWardResponse_Error)(nil),
	}
	file_market_location_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*GetLocationResponse_Data_)(nil),
		(*GetLocationResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_market_location_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_market_location_proto_goTypes,
		DependencyIndexes: file_market_location_proto_depIdxs,
		MessageInfos:      file_market_location_proto_msgTypes,
	}.Build()
	File_market_location_proto = out.File
	file_market_location_proto_rawDesc = nil
	file_market_location_proto_goTypes = nil
	file_market_location_proto_depIdxs = nil
}
