// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1-devel
// 	protoc        v3.21.8
// source: market/supervisor.proto

package market

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Supervisor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstName    string `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name"`
	MiddleName   string `protobuf:"bytes,2,opt,name=middle_name,json=middleName,proto3" json:"middle_name"`
	LastName     string `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name"`
	Position     string `protobuf:"bytes,4,opt,name=position,proto3" json:"position"`
	Telephone    string `protobuf:"bytes,5,opt,name=telephone,proto3" json:"telephone"`
	MobilePhone  string `protobuf:"bytes,6,opt,name=mobile_phone,json=mobilePhone,proto3" json:"mobile_phone"`
	Email        string `protobuf:"bytes,7,opt,name=email,proto3" json:"email"`
	SupervisorId string `protobuf:"bytes,8,opt,name=supervisor_id,json=supervisorId,proto3" json:"supervisor_id"`
}

func (x *Supervisor) Reset() {
	*x = Supervisor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_supervisor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Supervisor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Supervisor) ProtoMessage() {}

func (x *Supervisor) ProtoReflect() protoreflect.Message {
	mi := &file_market_supervisor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Supervisor.ProtoReflect.Descriptor instead.
func (*Supervisor) Descriptor() ([]byte, []int) {
	return file_market_supervisor_proto_rawDescGZIP(), []int{0}
}

func (x *Supervisor) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Supervisor) GetMiddleName() string {
	if x != nil {
		return x.MiddleName
	}
	return ""
}

func (x *Supervisor) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Supervisor) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *Supervisor) GetTelephone() string {
	if x != nil {
		return x.Telephone
	}
	return ""
}

func (x *Supervisor) GetMobilePhone() string {
	if x != nil {
		return x.MobilePhone
	}
	return ""
}

func (x *Supervisor) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Supervisor) GetSupervisorId() string {
	if x != nil {
		return x.SupervisorId
	}
	return ""
}

var File_market_supervisor_proto protoreflect.FileDescriptor

var file_market_supervisor_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2f, 0x73, 0x75, 0x70, 0x65, 0x72, 0x76, 0x69,
	0x73, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65,
	0x74, 0x22, 0x81, 0x02, 0x0a, 0x0a, 0x53, 0x75, 0x70, 0x65, 0x72, 0x76, 0x69, 0x73, 0x6f, 0x72,
	0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x65, 0x6c,
	0x65, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x65,
	0x6c, 0x65, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x6f, 0x62, 0x69, 0x6c,
	0x65, 0x5f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d,
	0x6f, 0x62, 0x69, 0x6c, 0x65, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x12, 0x23, 0x0a, 0x0d, 0x73, 0x75, 0x70, 0x65, 0x72, 0x76, 0x69, 0x73, 0x6f, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x75, 0x70, 0x65, 0x72, 0x76, 0x69,
	0x73, 0x6f, 0x72, 0x49, 0x64, 0x42, 0x31, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x72, 0x73,
	0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x50, 0x01, 0x5a, 0x1d, 0x67, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x2f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_market_supervisor_proto_rawDescOnce sync.Once
	file_market_supervisor_proto_rawDescData = file_market_supervisor_proto_rawDesc
)

func file_market_supervisor_proto_rawDescGZIP() []byte {
	file_market_supervisor_proto_rawDescOnce.Do(func() {
		file_market_supervisor_proto_rawDescData = protoimpl.X.CompressGZIP(file_market_supervisor_proto_rawDescData)
	})
	return file_market_supervisor_proto_rawDescData
}

var file_market_supervisor_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_market_supervisor_proto_goTypes = []interface{}{
	(*Supervisor)(nil), // 0: market.Supervisor
}
var file_market_supervisor_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_market_supervisor_proto_init() }
func file_market_supervisor_proto_init() {
	if File_market_supervisor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_market_supervisor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Supervisor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_market_supervisor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_market_supervisor_proto_goTypes,
		DependencyIndexes: file_market_supervisor_proto_depIdxs,
		MessageInfos:      file_market_supervisor_proto_msgTypes,
	}.Build()
	File_market_supervisor_proto = out.File
	file_market_supervisor_proto_rawDesc = nil
	file_market_supervisor_proto_goTypes = nil
	file_market_supervisor_proto_depIdxs = nil
}
