basePath: /
definitions:
  account.AuthResponse:
    properties:
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      roles:
        items:
          type: string
        type: array
      user_id:
        type: string
      username:
        type: string
    type: object
  account.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  account.LoginResponse_Data:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
      user:
        $ref: '#/definitions/account.AuthResponse'
    type: object
  account.UpsertUserRequest:
    properties:
      email:
        description: Insert only
        type: string
      first_name:
        type: string
      last_name:
        type: string
      middle_name:
        type: string
      role_ids:
        description: repeated string market_codes = 13;
        items:
          type: string
        type: array
      status:
        type: integer
    type: object
  common.Error:
    properties:
      code:
        type: integer
      details:
        additionalProperties:
          type: string
        type: object
      exception:
        type: string
      message:
        type: string
    type: object
  common.NoContentResponse:
    properties:
      error:
        $ref: '#/definitions/common.Error'
      success:
        type: boolean
    type: object
  model.ErrorResponse:
    properties:
      error_code:
        type: string
      error_description:
        type: string
      errors:
        additionalProperties:
          type: string
        type: object
      exception:
        type: string
    type: object
  model.FileResponse:
    properties:
      access_id:
        type: string
      content:
        type: string
      pre_signed_url:
        type: string
    type: object
  model.RentalAttachmentRequest:
    properties:
      attachment:
        items:
          type: integer
        type: array
    type: object
info:
  contact:
    email: hoanggg2110@gmail.com.vn
    name: 'Developer: Hoang Ngo'
  description: This is a documents for Rental System REST API.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: MHMarket REST API
  version: "1.0"
paths:
  /api/v2/files/upload:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: Body
        in: body
        name: _
        required: true
        schema:
          $ref: '#/definitions/model.RentalAttachmentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.FileResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Upload attachment
      tags:
      - File
  /api/v2/login:
    post:
      consumes:
      - application/json
      description: Get Access Token and Refresh Token
      parameters:
      - description: Login Information
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/account.LoginRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/account.LoginResponse_Data'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Login
      tags:
      - Auth
  /api/v2/logout:
    post:
      consumes:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Logout
      tags:
      - Auth
  /api/v2/users:
    post:
      consumes:
      - application/json
      parameters:
      - description: User Information
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/account.UpsertUserRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.NoContentResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Create User
      tags:
      - User
schemes:
- https
securityDefinitions:
  Bearer Token:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
